syntax = "proto3";

package guru.example.v1;

import "gogoproto/gogo.proto";
import "guru/example/v1/types.proto";

option go_package = "github.com/gurufinglobal/guru/v3/x/example/types";

// GenesisState defines x/example genesis state.
message GenesisState {
  Params params = 1 [(gogoproto.nullable) = false];

  // Sequence snapshots for deterministic restore.
  uint64 next_project_id = 2;
  uint64 next_task_id = 3;
  uint64 next_task_event_id = 4;

  repeated Project projects = 10 [(gogoproto.nullable) = false];
  repeated ProjectMember members = 11 [(gogoproto.nullable) = false];
  repeated Task tasks = 12 [(gogoproto.nullable) = false];
  repeated TaskEvent task_events = 13 [(gogoproto.nullable) = false];
}
