package types

import (
	errorsmod "cosmossdk.io/errors"
)

// IBC transfer sentinel errors
var (
	ErrInvalidPacketTimeout    = errorsmod.Register(ModuleName, 2, "invalid packet timeout")
	ErrInvalidDenomForTransfer = errorsmod.Register(ModuleName, 3, "invalid denomination for cross-chain transfer")
	ErrInvalidVersion          = errorsmod.Register(ModuleName, 4, "invalid ICS20 version")
	ErrInvalidAmount           = errorsmod.Register(ModuleName, 5, "invalid token amount")
	ErrDenomNotFound           = errorsmod.Register(ModuleName, 6, "denomination not found")
	ErrSendDisabled            = errorsmod.Register(ModuleName, 7, "fungible token transfers from this chain are disabled")
	ErrReceiveDisabled         = errorsmod.Register(ModuleName, 8, "fungible token transfers to this chain are disabled")
	ErrMaxTransferChannels     = errorsmod.Register(ModuleName, 9, "max transfer channels")
	ErrInvalidAuthorization    = errorsmod.Register(ModuleName, 10, "invalid transfer authorization")
	ErrInvalidMemo             = errorsmod.Register(ModuleName, 11, "invalid memo")
	ErrForwardedPacketTimedOut = errorsmod.Register(ModuleName, 12, "forwarded packet timed out")
	ErrForwardedPacketFailed   = errorsmod.Register(ModuleName, 13, "forwarded packet failed")
	ErrAbiEncoding             = errorsmod.Register(ModuleName, 14, "encoding abi failed")
	ErrAbiDecoding             = errorsmod.Register(ModuleName, 15, "decoding abi failed")
	ErrReceiveFailed           = errorsmod.Register(ModuleName, 16, "receive packet failed")
	ErrReadGenesisField        = errorsmod.Register(ModuleName, 17, "failed to read genesis field")
	ErrDecodeGenesisField      = errorsmod.Register(ModuleName, 18, "failed to decode genesis field")
	ErrOpenGenesisTargetField  = errorsmod.Register(ModuleName, 19, "failed to open genesis target field")
	ErrNilGenesisTargetWriter  = errorsmod.Register(ModuleName, 20, "genesis target field writer is nil")
	ErrEncodeGenesisField      = errorsmod.Register(ModuleName, 21, "failed to encode genesis field")
	ErrCloseGenesisFieldWriter = errorsmod.Register(ModuleName, 22, "failed to close genesis field writer")
	ErrInvalidParams           = errorsmod.Register(ModuleName, 23, "invalid transwap parameters")
	ErrRefundNotFound          = errorsmod.Register(ModuleName, 24, "refund not found")
	ErrInvalidRefundState      = errorsmod.Register(ModuleName, 25, "invalid refund state transition")
	ErrRefundPacketNotActive   = errorsmod.Register(ModuleName, 26, "refund packet is not active")
	ErrRefundRetryExhausted    = errorsmod.Register(ModuleName, 27, "refund retry limit reached")
	ErrRefundNotClaimable      = errorsmod.Register(ModuleName, 28, "refund is not manually claimable")
	ErrRefundUnauthorized      = errorsmod.Register(ModuleName, 29, "refund claimant is not the receiver")
	ErrUnsafeRefundTimeout     = errorsmod.Register(ModuleName, 30, "unsafe refund transport timeout")
	ErrRefundEscrowInvariant   = errorsmod.Register(ModuleName, 31, "refund escrow invariant violation")
	ErrInvalidAuthority        = errorsmod.Register(ModuleName, 32, "invalid authority")
	ErrRefundDispatchFailed    = errorsmod.Register(ModuleName, 33, "refund packet dispatch failed")
	ErrInvalidExchangeID       = errorsmod.Register(ModuleName, 34, "invalid exchange id")
	ErrInvalidSwapProtection   = errorsmod.Register(ModuleName, 35, "invalid swap protection")
	ErrMinimumAmountOut        = errorsmod.Register(ModuleName, 36, "minimum amount out not satisfied")
	ErrRefundRetryNotDue       = errorsmod.Register(ModuleName, 37, "refund retry is not due")
)
