package types

// IBC transfer events
const (
	EventTypeTimeout             = "timeout"
	EventTypePacket              = "fungible_token_packet"
	EventTypeTransfer            = "ibc_transfer"
	EventTypeChannelClose        = "channel_closed"
	EventTypeDenom               = "denomination"
	EventTypeRefundCreated       = "transwap_refund_created"
	EventTypeRefundStateChanged  = "transwap_refund_state_changed"
	EventTypeRefundAttempt       = "transwap_refund_attempt"
	EventTypeRefundAttemptFailed = "transwap_refund_attempt_failed"
	EventTypeRefundClaimed       = "transwap_refund_claimed"

	AttributeKeySender          = "sender"
	AttributeKeyReceiver        = "receiver"
	AttributeKeyDenom           = "denom"
	AttributeKeyDenomHash       = "denom_hash"
	AttributeKeyAmount          = "amount"
	AttributeKeyRefundReceiver  = "refund_receiver"
	AttributeKeyRefundTokens    = "refund_tokens"
	AttributeKeyAckSuccess      = "success"
	AttributeKeyAck             = "acknowledgement"
	AttributeKeyAckError        = "error"
	AttributeKeyMemo            = "memo"
	AttributeKeyRefundID        = "refund_id"
	AttributeKeyRefundStatus    = "refund_status"
	AttributeKeyRetryCount      = "retry_count"
	AttributeKeyPacketSequence  = "packet_sequence"
	AttributeKeyPacketTimeout   = "packet_timeout"
	AttributeKeyClaimAddress    = "claim_address"
	AttributeKeyFailureReason   = "failure_reason"
	AttributeKeyNextRetryHeight = "next_retry_height"
)
