syntax = "proto3";
package guru.oracle.v1;

import "cosmos/query/v1/query.proto";
import "google/api/annotations.proto";
import "guru/oracle/v1/oracle.proto";
import "guru/oracle/v1/params.proto";

option go_package = "github.com/gurufinglobal/guru/v3/api/guru/oracle/v1;oraclev1";

service Query {
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/guru/oracle/v1/params";
    option (cosmos.query.v1.module_query_safe) = true;
  }

  rpc ActiveTasks(QueryActiveTasksRequest) returns (QueryActiveTasksResponse) {
    option (google.api.http).get = "/guru/oracle/v1/tasks";
    option (cosmos.query.v1.module_query_safe) = true;
  }

  rpc OracleValue(QueryOracleValueRequest)
      returns (QueryOracleValueResponse) {
    option (google.api.http).get = "/guru/oracle/v1/oracle_values/{symbol}";
    option (cosmos.query.v1.module_query_safe) = true;
  }

  rpc OracleValues(QueryOracleValuesRequest)
      returns (QueryOracleValuesResponse) {
    option (google.api.http).get = "/guru/oracle/v1/oracle_values";
    option (cosmos.query.v1.module_query_safe) = true;
  }
}

message QueryParamsRequest {}
message QueryParamsResponse { Params params = 1; }

message QueryActiveTasksRequest {}
message QueryActiveTasksResponse { repeated OracleTask tasks = 1; }

message QueryOracleValueRequest { string symbol = 1; }
message QueryOracleValueResponse { OracleResult result = 1; }

message QueryOracleValuesRequest {}
message QueryOracleValuesResponse { repeated OracleResult results = 1; }