syntax = "proto3";
package guru.oracle.v1;

import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "guru/oracle/v1/oracle.proto";
import "guru/oracle/v1/params.proto";

option go_package = "github.com/gurufinglobal/guru/v3/api/guru/oracle/v1;oraclev1";

service Msg {
  option (cosmos.msg.v1.service) = true;

  // UpdateParams defines a governance operation for updating the parameters.
  rpc UpdateParams(MsgUpdateParams) returns (MsgUpdateParamsResponse);

  // UpdateOracleTask is called by governance or authority to manage tasks.
  rpc UpdateOracleTask(MsgUpdateOracleTask)
      returns (MsgUpdateOracleTaskResponse);

  // UpdatePrices is a system message injected during PrepareProposal.
  rpc UpdatePrices(MsgUpdatePrices) returns (MsgUpdatePricesResponse);
}

message MsgUpdateParams {
  option (cosmos.msg.v1.signer) = "authority";
  string authority = 1 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
  Params params = 2;
}
message MsgUpdateParamsResponse {}

message MsgUpdateOracleTask {
  option (cosmos.msg.v1.signer) = "authority";
  string authority = 1 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
  OracleTask task = 2;
  bool is_remove = 3;
}
message MsgUpdateOracleTaskResponse {}

message MsgUpdatePrices {
  option (cosmos.msg.v1.signer) = "authority";
  // 오라클 모듈 자체의 계정 주소가 서명자로 들어갑니다 (system tx).
  string authority = 1 [ (cosmos_proto.scalar) = "cosmos.AddressString" ];
  repeated OracleResult rates = 2;
}
message MsgUpdatePricesResponse {}