// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: guru/oracle/v2/query.proto

package oraclev2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName           = "/guru.oracle.v2.Query/Params"
	Query_ModeratorAddress_FullMethodName = "/guru.oracle.v2.Query/ModeratorAddress"
	Query_OracleRequest_FullMethodName    = "/guru.oracle.v2.Query/OracleRequest"
	Query_OracleRequests_FullMethodName   = "/guru.oracle.v2.Query/OracleRequests"
	Query_OracleReports_FullMethodName    = "/guru.oracle.v2.Query/OracleReports"
	Query_OracleResult_FullMethodName     = "/guru.oracle.v2.Query/OracleResult"
	Query_OracleResults_FullMethodName    = "/guru.oracle.v2.Query/OracleResults"
	Query_Categories_FullMethodName       = "/guru.oracle.v2.Query/Categories"
	Query_Whitelist_FullMethodName        = "/guru.oracle.v2.Query/Whitelist"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the current module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// ModeratorAddress returns the oracle moderator address.
	ModeratorAddress(ctx context.Context, in *QueryModeratorAddressRequest, opts ...grpc.CallOption) (*QueryModeratorAddressResponse, error)
	// OracleRequest returns a single oracle request by id.
	OracleRequest(ctx context.Context, in *QueryOracleRequestRequest, opts ...grpc.CallOption) (*QueryOracleRequestResponse, error)
	// OracleRequests returns oracle requests with optional filters.
	OracleRequests(ctx context.Context, in *QueryOracleRequestsRequest, opts ...grpc.CallOption) (*QueryOracleRequestsResponse, error)
	// [수정] OracleReports RPC 추가 (메시지는 있었으나 RPC가 없었음)
	// 특정 Request에 대해 제출된 개별 Report들을 조회
	OracleReports(ctx context.Context, in *QueryOracleReportsRequest, opts ...grpc.CallOption) (*QueryOracleReportsResponse, error)
	// OracleResult returns a specific aggregated result (single lookup).
	// 보통 최신 결과 혹은 특정 nonce의 결과를 조회할 때 사용
	OracleResult(ctx context.Context, in *QueryOracleResultRequest, opts ...grpc.CallOption) (*QueryOracleResultResponse, error)
	// [수정] OracleResults는 보통 특정 Request의 "과거 이력(History)"을 조회하는
	// 용도입니다. 따라서 path를 results/{request_id} 형식이 아닌
	// requests/{request_id}/results 로 잡는 게 자연스럽습니다.
	OracleResults(ctx context.Context, in *QueryOracleResultsRequest, opts ...grpc.CallOption) (*QueryOracleResultsResponse, error)
	// Categories returns enabled categories.
	Categories(ctx context.Context, in *QueryCategoriesRequest, opts ...grpc.CallOption) (*QueryCategoriesResponse, error)
	// Whitelist returns whitelisted provider addresses and count.
	Whitelist(ctx context.Context, in *QueryWhitelistRequest, opts ...grpc.CallOption) (*QueryWhitelistResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ModeratorAddress(ctx context.Context, in *QueryModeratorAddressRequest, opts ...grpc.CallOption) (*QueryModeratorAddressResponse, error) {
	out := new(QueryModeratorAddressResponse)
	err := c.cc.Invoke(ctx, Query_ModeratorAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OracleRequest(ctx context.Context, in *QueryOracleRequestRequest, opts ...grpc.CallOption) (*QueryOracleRequestResponse, error) {
	out := new(QueryOracleRequestResponse)
	err := c.cc.Invoke(ctx, Query_OracleRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OracleRequests(ctx context.Context, in *QueryOracleRequestsRequest, opts ...grpc.CallOption) (*QueryOracleRequestsResponse, error) {
	out := new(QueryOracleRequestsResponse)
	err := c.cc.Invoke(ctx, Query_OracleRequests_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OracleReports(ctx context.Context, in *QueryOracleReportsRequest, opts ...grpc.CallOption) (*QueryOracleReportsResponse, error) {
	out := new(QueryOracleReportsResponse)
	err := c.cc.Invoke(ctx, Query_OracleReports_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OracleResult(ctx context.Context, in *QueryOracleResultRequest, opts ...grpc.CallOption) (*QueryOracleResultResponse, error) {
	out := new(QueryOracleResultResponse)
	err := c.cc.Invoke(ctx, Query_OracleResult_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OracleResults(ctx context.Context, in *QueryOracleResultsRequest, opts ...grpc.CallOption) (*QueryOracleResultsResponse, error) {
	out := new(QueryOracleResultsResponse)
	err := c.cc.Invoke(ctx, Query_OracleResults_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Categories(ctx context.Context, in *QueryCategoriesRequest, opts ...grpc.CallOption) (*QueryCategoriesResponse, error) {
	out := new(QueryCategoriesResponse)
	err := c.cc.Invoke(ctx, Query_Categories_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Whitelist(ctx context.Context, in *QueryWhitelistRequest, opts ...grpc.CallOption) (*QueryWhitelistResponse, error) {
	out := new(QueryWhitelistResponse)
	err := c.cc.Invoke(ctx, Query_Whitelist_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Params returns the current module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// ModeratorAddress returns the oracle moderator address.
	ModeratorAddress(context.Context, *QueryModeratorAddressRequest) (*QueryModeratorAddressResponse, error)
	// OracleRequest returns a single oracle request by id.
	OracleRequest(context.Context, *QueryOracleRequestRequest) (*QueryOracleRequestResponse, error)
	// OracleRequests returns oracle requests with optional filters.
	OracleRequests(context.Context, *QueryOracleRequestsRequest) (*QueryOracleRequestsResponse, error)
	// [수정] OracleReports RPC 추가 (메시지는 있었으나 RPC가 없었음)
	// 특정 Request에 대해 제출된 개별 Report들을 조회
	OracleReports(context.Context, *QueryOracleReportsRequest) (*QueryOracleReportsResponse, error)
	// OracleResult returns a specific aggregated result (single lookup).
	// 보통 최신 결과 혹은 특정 nonce의 결과를 조회할 때 사용
	OracleResult(context.Context, *QueryOracleResultRequest) (*QueryOracleResultResponse, error)
	// [수정] OracleResults는 보통 특정 Request의 "과거 이력(History)"을 조회하는
	// 용도입니다. 따라서 path를 results/{request_id} 형식이 아닌
	// requests/{request_id}/results 로 잡는 게 자연스럽습니다.
	OracleResults(context.Context, *QueryOracleResultsRequest) (*QueryOracleResultsResponse, error)
	// Categories returns enabled categories.
	Categories(context.Context, *QueryCategoriesRequest) (*QueryCategoriesResponse, error)
	// Whitelist returns whitelisted provider addresses and count.
	Whitelist(context.Context, *QueryWhitelistRequest) (*QueryWhitelistResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) ModeratorAddress(context.Context, *QueryModeratorAddressRequest) (*QueryModeratorAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModeratorAddress not implemented")
}
func (UnimplementedQueryServer) OracleRequest(context.Context, *QueryOracleRequestRequest) (*QueryOracleRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OracleRequest not implemented")
}
func (UnimplementedQueryServer) OracleRequests(context.Context, *QueryOracleRequestsRequest) (*QueryOracleRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OracleRequests not implemented")
}
func (UnimplementedQueryServer) OracleReports(context.Context, *QueryOracleReportsRequest) (*QueryOracleReportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OracleReports not implemented")
}
func (UnimplementedQueryServer) OracleResult(context.Context, *QueryOracleResultRequest) (*QueryOracleResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OracleResult not implemented")
}
func (UnimplementedQueryServer) OracleResults(context.Context, *QueryOracleResultsRequest) (*QueryOracleResultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OracleResults not implemented")
}
func (UnimplementedQueryServer) Categories(context.Context, *QueryCategoriesRequest) (*QueryCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Categories not implemented")
}
func (UnimplementedQueryServer) Whitelist(context.Context, *QueryWhitelistRequest) (*QueryWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Whitelist not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ModeratorAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryModeratorAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ModeratorAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ModeratorAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ModeratorAddress(ctx, req.(*QueryModeratorAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OracleRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOracleRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OracleRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_OracleRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OracleRequest(ctx, req.(*QueryOracleRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OracleRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOracleRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OracleRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_OracleRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OracleRequests(ctx, req.(*QueryOracleRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OracleReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOracleReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OracleReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_OracleReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OracleReports(ctx, req.(*QueryOracleReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OracleResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOracleResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OracleResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_OracleResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OracleResult(ctx, req.(*QueryOracleResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OracleResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOracleResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OracleResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_OracleResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OracleResults(ctx, req.(*QueryOracleResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Categories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Categories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Categories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Categories(ctx, req.(*QueryCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Whitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Whitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Whitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Whitelist(ctx, req.(*QueryWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "guru.oracle.v2.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ModeratorAddress",
			Handler:    _Query_ModeratorAddress_Handler,
		},
		{
			MethodName: "OracleRequest",
			Handler:    _Query_OracleRequest_Handler,
		},
		{
			MethodName: "OracleRequests",
			Handler:    _Query_OracleRequests_Handler,
		},
		{
			MethodName: "OracleReports",
			Handler:    _Query_OracleReports_Handler,
		},
		{
			MethodName: "OracleResult",
			Handler:    _Query_OracleResult_Handler,
		},
		{
			MethodName: "OracleResults",
			Handler:    _Query_OracleResults_Handler,
		},
		{
			MethodName: "Categories",
			Handler:    _Query_Categories_Handler,
		},
		{
			MethodName: "Whitelist",
			Handler:    _Query_Whitelist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guru/oracle/v2/query.proto",
}
