// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: guru/oracle/v2/tx.proto

package oraclev2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateModeratorAddress_FullMethodName = "/guru.oracle.v2.Msg/UpdateModeratorAddress"
	Msg_RegisterOracleRequest_FullMethodName  = "/guru.oracle.v2.Msg/RegisterOracleRequest"
	Msg_UpdateOracleRequest_FullMethodName    = "/guru.oracle.v2.Msg/UpdateOracleRequest"
	Msg_SubmitOracleReport_FullMethodName     = "/guru.oracle.v2.Msg/SubmitOracleReport"
	Msg_AddToWhitelist_FullMethodName         = "/guru.oracle.v2.Msg/AddToWhitelist"
	Msg_RemoveFromWhitelist_FullMethodName    = "/guru.oracle.v2.Msg/RemoveFromWhitelist"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateModeratorAddress defines a method to update the moderator address.
	UpdateModeratorAddress(ctx context.Context, in *MsgUpdateModeratorAddress, opts ...grpc.CallOption) (*MsgUpdateModeratorAddressResponse, error)
	// RegisterOracleRequest defines a method to register a new oracle request.
	RegisterOracleRequest(ctx context.Context, in *MsgRegisterOracleRequest, opts ...grpc.CallOption) (*MsgRegisterOracleRequestResponse, error)
	// UpdateOracleRequest defines a method to update an existing oracle request.
	UpdateOracleRequest(ctx context.Context, in *MsgUpdateOracleRequest, opts ...grpc.CallOption) (*MsgUpdateOracleRequestResponse, error)
	// SubmitOracleReport defines a method to submit a report for an oracle request.
	SubmitOracleReport(ctx context.Context, in *MsgSubmitOracleReport, opts ...grpc.CallOption) (*MsgSubmitOracleReportResponse, error)
	// Add an address to the oracle whitelist (moderator only).
	AddToWhitelist(ctx context.Context, in *MsgAddToWhitelist, opts ...grpc.CallOption) (*MsgAddToWhitelistResponse, error)
	// Remove an address from the oracle whitelist (moderator only).
	RemoveFromWhitelist(ctx context.Context, in *MsgRemoveFromWhitelist, opts ...grpc.CallOption) (*MsgRemoveFromWhitelistResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateModeratorAddress(ctx context.Context, in *MsgUpdateModeratorAddress, opts ...grpc.CallOption) (*MsgUpdateModeratorAddressResponse, error) {
	out := new(MsgUpdateModeratorAddressResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateModeratorAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterOracleRequest(ctx context.Context, in *MsgRegisterOracleRequest, opts ...grpc.CallOption) (*MsgRegisterOracleRequestResponse, error) {
	out := new(MsgRegisterOracleRequestResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterOracleRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateOracleRequest(ctx context.Context, in *MsgUpdateOracleRequest, opts ...grpc.CallOption) (*MsgUpdateOracleRequestResponse, error) {
	out := new(MsgUpdateOracleRequestResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateOracleRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitOracleReport(ctx context.Context, in *MsgSubmitOracleReport, opts ...grpc.CallOption) (*MsgSubmitOracleReportResponse, error) {
	out := new(MsgSubmitOracleReportResponse)
	err := c.cc.Invoke(ctx, Msg_SubmitOracleReport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddToWhitelist(ctx context.Context, in *MsgAddToWhitelist, opts ...grpc.CallOption) (*MsgAddToWhitelistResponse, error) {
	out := new(MsgAddToWhitelistResponse)
	err := c.cc.Invoke(ctx, Msg_AddToWhitelist_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveFromWhitelist(ctx context.Context, in *MsgRemoveFromWhitelist, opts ...grpc.CallOption) (*MsgRemoveFromWhitelistResponse, error) {
	out := new(MsgRemoveFromWhitelistResponse)
	err := c.cc.Invoke(ctx, Msg_RemoveFromWhitelist_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateModeratorAddress defines a method to update the moderator address.
	UpdateModeratorAddress(context.Context, *MsgUpdateModeratorAddress) (*MsgUpdateModeratorAddressResponse, error)
	// RegisterOracleRequest defines a method to register a new oracle request.
	RegisterOracleRequest(context.Context, *MsgRegisterOracleRequest) (*MsgRegisterOracleRequestResponse, error)
	// UpdateOracleRequest defines a method to update an existing oracle request.
	UpdateOracleRequest(context.Context, *MsgUpdateOracleRequest) (*MsgUpdateOracleRequestResponse, error)
	// SubmitOracleReport defines a method to submit a report for an oracle request.
	SubmitOracleReport(context.Context, *MsgSubmitOracleReport) (*MsgSubmitOracleReportResponse, error)
	// Add an address to the oracle whitelist (moderator only).
	AddToWhitelist(context.Context, *MsgAddToWhitelist) (*MsgAddToWhitelistResponse, error)
	// Remove an address from the oracle whitelist (moderator only).
	RemoveFromWhitelist(context.Context, *MsgRemoveFromWhitelist) (*MsgRemoveFromWhitelistResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateModeratorAddress(context.Context, *MsgUpdateModeratorAddress) (*MsgUpdateModeratorAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModeratorAddress not implemented")
}
func (UnimplementedMsgServer) RegisterOracleRequest(context.Context, *MsgRegisterOracleRequest) (*MsgRegisterOracleRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterOracleRequest not implemented")
}
func (UnimplementedMsgServer) UpdateOracleRequest(context.Context, *MsgUpdateOracleRequest) (*MsgUpdateOracleRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOracleRequest not implemented")
}
func (UnimplementedMsgServer) SubmitOracleReport(context.Context, *MsgSubmitOracleReport) (*MsgSubmitOracleReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOracleReport not implemented")
}
func (UnimplementedMsgServer) AddToWhitelist(context.Context, *MsgAddToWhitelist) (*MsgAddToWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToWhitelist not implemented")
}
func (UnimplementedMsgServer) RemoveFromWhitelist(context.Context, *MsgRemoveFromWhitelist) (*MsgRemoveFromWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromWhitelist not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateModeratorAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateModeratorAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateModeratorAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateModeratorAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateModeratorAddress(ctx, req.(*MsgUpdateModeratorAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterOracleRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterOracleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterOracleRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterOracleRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterOracleRequest(ctx, req.(*MsgRegisterOracleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateOracleRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateOracleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateOracleRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateOracleRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateOracleRequest(ctx, req.(*MsgUpdateOracleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitOracleReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitOracleReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitOracleReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SubmitOracleReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitOracleReport(ctx, req.(*MsgSubmitOracleReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddToWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddToWhitelist)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddToWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AddToWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddToWhitelist(ctx, req.(*MsgAddToWhitelist))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveFromWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveFromWhitelist)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveFromWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RemoveFromWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveFromWhitelist(ctx, req.(*MsgRemoveFromWhitelist))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "guru.oracle.v2.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateModeratorAddress",
			Handler:    _Msg_UpdateModeratorAddress_Handler,
		},
		{
			MethodName: "RegisterOracleRequest",
			Handler:    _Msg_RegisterOracleRequest_Handler,
		},
		{
			MethodName: "UpdateOracleRequest",
			Handler:    _Msg_UpdateOracleRequest_Handler,
		},
		{
			MethodName: "SubmitOracleReport",
			Handler:    _Msg_SubmitOracleReport_Handler,
		},
		{
			MethodName: "AddToWhitelist",
			Handler:    _Msg_AddToWhitelist_Handler,
		},
		{
			MethodName: "RemoveFromWhitelist",
			Handler:    _Msg_RemoveFromWhitelist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guru/oracle/v2/tx.proto",
}
