package types

const (
	EventTypeAdminRegistered         = "admin_registered"
	EventTypeAdminUpdated            = "admin_updated"
	EventTypeAdminRemoved            = "admin_removed"
	EventTypeExchangeRegistered      = "exchange_registered"
	EventTypeExchangeUpdated         = "exchange_updated"
	EventTypeExchangeStatus          = "exchange_status_changed"
	EventTypeExchangeDeleted         = "exchange_deleted"
	EventTypeReserveDeposited        = "reserve_deposited"
	EventTypeReserveDepositorAdded   = "reserve_depositor_added"
	EventTypeReserveDepositorRemoved = "reserve_depositor_removed"
	EventTypeReserveWithdrawn        = "reserve_withdrawn"
	EventTypeFeesCollected           = "fees_collected"
	EventTypeFeesLocked              = "fees_locked"
	EventTypeFeesReleased            = "fees_released"
	EventTypeFeesRefunded            = "fees_refunded"
	EventTypeFeesWithdrawn           = "fees_withdrawn"
	EventTypeVolumeEpochActivated    = "volume_epoch_activated"
	EventTypeVolumeRecorded          = "volume_recorded"
	EventTypeVolumeReleased          = "volume_released"
)

const (
	AttributeKeyAdmin          = "admin"
	AttributeKeyBexAdmin       = "bex_admin"
	AttributeKeyPreviousAdmin  = "previous_admin"
	AttributeKeyModerator      = "moderator"
	AttributeKeyExchangeID     = "exchange_id"
	AttributeKeyReserveAddress = "reserve_address"
	AttributeKeyDepositor      = "depositor"
	AttributeKeyRecipient      = "recipient"
	AttributeKeyAmount         = "amount"
	AttributeKeyDirection      = "direction"
	AttributeKeyRevision       = "revision"
	AttributeKeyStatus         = "status"
	AttributeKeyPreviousStatus = "previous_status"
	AttributeKeyCurrentAmount  = "current_amount"
	AttributeKeyEpochSeconds   = "epoch_seconds"
	AttributeKeyPreviousEpoch  = "previous_epoch_seconds"
	AttributeKeyEffectiveAt    = "effective_at_unix"
	AttributeKeyGeneration     = "volume_window_generation"
)
