// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: guru/feepolicy/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterDiscounts struct {
	ModeratorAddress string            `protobuf:"bytes,1,opt,name=moderator_address,json=moderatorAddress,proto3" json:"moderator_address,omitempty"`
	Discounts        []AccountDiscount `protobuf:"bytes,2,rep,name=discounts,proto3" json:"discounts"`
}

func (m *MsgRegisterDiscounts) Reset()         { *m = MsgRegisterDiscounts{} }
func (m *MsgRegisterDiscounts) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterDiscounts) ProtoMessage()    {}
func (*MsgRegisterDiscounts) Descriptor() ([]byte, []int) {
	return fileDescriptor_c949a76985d4588d, []int{0}
}
func (m *MsgRegisterDiscounts) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterDiscounts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterDiscounts.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterDiscounts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterDiscounts.Merge(m, src)
}
func (m *MsgRegisterDiscounts) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterDiscounts) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterDiscounts.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterDiscounts proto.InternalMessageInfo

type MsgRegisterDiscountsResponse struct {
}

func (m *MsgRegisterDiscountsResponse) Reset()         { *m = MsgRegisterDiscountsResponse{} }
func (m *MsgRegisterDiscountsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterDiscountsResponse) ProtoMessage()    {}
func (*MsgRegisterDiscountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c949a76985d4588d, []int{1}
}
func (m *MsgRegisterDiscountsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterDiscountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterDiscountsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterDiscountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterDiscountsResponse.Merge(m, src)
}
func (m *MsgRegisterDiscountsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterDiscountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterDiscountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterDiscountsResponse proto.InternalMessageInfo

type MsgRemoveDiscounts struct {
	ModeratorAddress string `protobuf:"bytes,1,opt,name=moderator_address,json=moderatorAddress,proto3" json:"moderator_address,omitempty"`
	Address          string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Module           string `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	MsgType          string `protobuf:"bytes,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
}

func (m *MsgRemoveDiscounts) Reset()         { *m = MsgRemoveDiscounts{} }
func (m *MsgRemoveDiscounts) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveDiscounts) ProtoMessage()    {}
func (*MsgRemoveDiscounts) Descriptor() ([]byte, []int) {
	return fileDescriptor_c949a76985d4588d, []int{2}
}
func (m *MsgRemoveDiscounts) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveDiscounts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveDiscounts.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveDiscounts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveDiscounts.Merge(m, src)
}
func (m *MsgRemoveDiscounts) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveDiscounts) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveDiscounts.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveDiscounts proto.InternalMessageInfo

type MsgRemoveDiscountsResponse struct {
}

func (m *MsgRemoveDiscountsResponse) Reset()         { *m = MsgRemoveDiscountsResponse{} }
func (m *MsgRemoveDiscountsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveDiscountsResponse) ProtoMessage()    {}
func (*MsgRemoveDiscountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c949a76985d4588d, []int{3}
}
func (m *MsgRemoveDiscountsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveDiscountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveDiscountsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveDiscountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveDiscountsResponse.Merge(m, src)
}
func (m *MsgRemoveDiscountsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveDiscountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveDiscountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveDiscountsResponse proto.InternalMessageInfo

// msg declaration for changing the moderator.
type MsgChangeModerator struct {
	ModeratorAddress    string `protobuf:"bytes,1,opt,name=moderator_address,json=moderatorAddress,proto3" json:"moderator_address,omitempty"`
	NewModeratorAddress string `protobuf:"bytes,2,opt,name=new_moderator_address,json=newModeratorAddress,proto3" json:"new_moderator_address,omitempty"`
}

func (m *MsgChangeModerator) Reset()         { *m = MsgChangeModerator{} }
func (m *MsgChangeModerator) String() string { return proto.CompactTextString(m) }
func (*MsgChangeModerator) ProtoMessage()    {}
func (*MsgChangeModerator) Descriptor() ([]byte, []int) {
	return fileDescriptor_c949a76985d4588d, []int{4}
}
func (m *MsgChangeModerator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgChangeModerator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgChangeModerator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgChangeModerator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChangeModerator.Merge(m, src)
}
func (m *MsgChangeModerator) XXX_Size() int {
	return m.Size()
}
func (m *MsgChangeModerator) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChangeModerator.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChangeModerator proto.InternalMessageInfo

// Response type for the Msg/ChangeModerator.
type MsgChangeModeratorResponse struct {
}

func (m *MsgChangeModeratorResponse) Reset()         { *m = MsgChangeModeratorResponse{} }
func (m *MsgChangeModeratorResponse) String() string { return proto.CompactTextString(m) }
func (*MsgChangeModeratorResponse) ProtoMessage()    {}
func (*MsgChangeModeratorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c949a76985d4588d, []int{5}
}
func (m *MsgChangeModeratorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgChangeModeratorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgChangeModeratorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgChangeModeratorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChangeModeratorResponse.Merge(m, src)
}
func (m *MsgChangeModeratorResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgChangeModeratorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChangeModeratorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChangeModeratorResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterDiscounts)(nil), "guru.feepolicy.v1.MsgRegisterDiscounts")
	proto.RegisterType((*MsgRegisterDiscountsResponse)(nil), "guru.feepolicy.v1.MsgRegisterDiscountsResponse")
	proto.RegisterType((*MsgRemoveDiscounts)(nil), "guru.feepolicy.v1.MsgRemoveDiscounts")
	proto.RegisterType((*MsgRemoveDiscountsResponse)(nil), "guru.feepolicy.v1.MsgRemoveDiscountsResponse")
	proto.RegisterType((*MsgChangeModerator)(nil), "guru.feepolicy.v1.MsgChangeModerator")
	proto.RegisterType((*MsgChangeModeratorResponse)(nil), "guru.feepolicy.v1.MsgChangeModeratorResponse")
}

func init() { proto.RegisterFile("guru/feepolicy/v1/tx.proto", fileDescriptor_c949a76985d4588d) }

var fileDescriptor_c949a76985d4588d = []byte{
	// 575 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x3f, 0x6f, 0xd3, 0x4e,
	0x18, 0xf6, 0x25, 0xfd, 0xf5, 0x47, 0x8f, 0x01, 0x62, 0x02, 0xb8, 0x56, 0xe4, 0x94, 0xa0, 0x8a,
	0x28, 0x52, 0x7d, 0x24, 0x6c, 0xdd, 0x1a, 0xfe, 0x4c, 0xcd, 0x12, 0x98, 0x58, 0x22, 0xc7, 0xb9,
	0x5e, 0x2d, 0xd9, 0x77, 0x96, 0xef, 0xec, 0x36, 0x1b, 0xea, 0xc4, 0x88, 0xc4, 0xc0, 0x48, 0x3f,
	0x42, 0x07, 0xbe, 0x02, 0x52, 0xd8, 0x2a, 0x58, 0x98, 0x10, 0x4a, 0x90, 0xca, 0xc7, 0x40, 0xfe,
	0x1b, 0xb0, 0x13, 0x25, 0x43, 0xb7, 0xbb, 0x7b, 0xde, 0xe7, 0x7d, 0x9f, 0xe7, 0xfc, 0x9c, 0xa1,
	0x4a, 0x7c, 0xcf, 0x47, 0x47, 0x18, 0xbb, 0xcc, 0xb6, 0xcc, 0x31, 0x0a, 0xda, 0x48, 0x9c, 0xea,
	0xae, 0xc7, 0x04, 0x93, 0x2b, 0x21, 0xa6, 0x67, 0x98, 0x1e, 0xb4, 0xd5, 0x07, 0xc5, 0xf2, 0x39,
	0x1e, 0xb1, 0xd4, 0x2a, 0x61, 0x84, 0x45, 0x4b, 0x14, 0xae, 0x92, 0xd3, 0x1a, 0x61, 0x8c, 0xd8,
	0x18, 0x19, 0xae, 0x85, 0x0c, 0x4a, 0x99, 0x30, 0x84, 0xc5, 0x28, 0x4f, 0x50, 0xcd, 0x64, 0xdc,
	0x61, 0x1c, 0x0d, 0x0d, 0x8e, 0x51, 0xd0, 0x1e, 0x62, 0x61, 0xb4, 0x91, 0xc9, 0x2c, 0x9a, 0xe0,
	0xf7, 0x13, 0xdc, 0xe1, 0x24, 0x1c, 0xe9, 0x70, 0x92, 0x00, 0xdb, 0x31, 0x30, 0x88, 0xe7, 0xc5,
	0x9b, 0x18, 0x6a, 0x7c, 0x06, 0xb0, 0xda, 0xe3, 0xa4, 0x8f, 0x89, 0xc5, 0x05, 0xf6, 0x9e, 0x59,
	0xdc, 0x64, 0x3e, 0x15, 0x5c, 0x7e, 0x0e, 0x2b, 0x0e, 0x1b, 0x61, 0xcf, 0x10, 0xcc, 0x1b, 0x18,
	0xa3, 0x91, 0x87, 0x39, 0x57, 0xc0, 0x0e, 0x68, 0x6e, 0x75, 0x95, 0xaf, 0x9f, 0xf6, 0xaa, 0x49,
	0x97, 0x83, 0x18, 0x79, 0x29, 0x3c, 0x8b, 0x92, 0xfe, 0xed, 0x8c, 0x92, 0x9c, 0xcb, 0x2f, 0xe0,
	0xd6, 0x28, 0xed, 0xa9, 0x94, 0x76, 0xca, 0xcd, 0x9b, 0x9d, 0x86, 0x5e, 0xb8, 0x31, 0xfd, 0xc0,
	0x8c, 0x4a, 0xd2, 0xf1, 0xdd, 0x8d, 0xc9, 0x8f, 0xba, 0xd4, 0x9f, 0x53, 0xf7, 0xb5, 0xb7, 0xe7,
	0x75, 0xe9, 0xf7, 0x79, 0x5d, 0x3a, 0xbb, 0xba, 0x68, 0x15, 0x95, 0x35, 0x34, 0x58, 0x5b, 0x64,
	0xa3, 0x8f, 0xb9, 0xcb, 0x28, 0xc7, 0x8d, 0x09, 0x80, 0x72, 0x54, 0xe0, 0xb0, 0x00, 0x5f, 0xbb,
	0x4b, 0x05, 0xfe, 0x9f, 0x92, 0x4b, 0x21, 0xb9, 0x9f, 0x6e, 0xe5, 0x7b, 0x70, 0xd3, 0x61, 0x23,
	0xdf, 0xc6, 0x4a, 0x39, 0x02, 0x92, 0x9d, 0xbc, 0x0d, 0x6f, 0x38, 0x9c, 0x0c, 0xc4, 0xd8, 0xc5,
	0xca, 0x46, 0x4c, 0x71, 0x38, 0x79, 0x35, 0x76, 0xf1, 0x4a, 0xab, 0x35, 0xa8, 0x16, 0x9d, 0x64,
	0x46, 0xbf, 0xc4, 0x46, 0x9f, 0x1e, 0x1b, 0x94, 0xe0, 0x5e, 0x4a, 0xbe, 0x2e, 0xa3, 0x87, 0xf0,
	0x2e, 0xc5, 0x27, 0x83, 0x62, 0xab, 0xd2, 0x8a, 0x56, 0x77, 0x28, 0x3e, 0xe9, 0xe5, 0xba, 0xad,
	0xe9, 0x34, 0x67, 0x25, 0x75, 0xda, 0x99, 0x96, 0x61, 0xb9, 0xc7, 0x89, 0xfc, 0x11, 0xc0, 0x4a,
	0x31, 0xbf, 0x8f, 0x16, 0xa4, 0x6c, 0x51, 0x42, 0x54, 0xb4, 0x66, 0x61, 0x76, 0xc3, 0x8f, 0xcf,
	0xbe, 0xfd, 0x7a, 0x5f, 0x6a, 0xed, 0x83, 0x56, 0x63, 0x17, 0x15, 0x5f, 0xba, 0x97, 0x10, 0x07,
	0x59, 0x78, 0xe5, 0x0f, 0x00, 0xde, 0xca, 0x27, 0x6f, 0x77, 0xd9, 0xd8, 0x7f, 0xca, 0xd4, 0xbd,
	0xb5, 0xca, 0x32, 0x6d, 0x7a, 0xa4, 0xad, 0x19, 0x6a, 0x7b, 0xb8, 0x50, 0x5b, 0x48, 0xcb, 0x29,
	0xcb, 0x47, 0x65, 0x89, 0xb2, 0x5c, 0xd9, 0x32, 0x65, 0x4b, 0xbe, 0xd6, 0x2a, 0x65, 0x66, 0x44,
	0x9b, 0x07, 0x4b, 0xfd, 0xef, 0xcd, 0xd5, 0x45, 0x0b, 0x74, 0x0f, 0x27, 0x53, 0x0d, 0x5c, 0x4e,
	0x35, 0xf0, 0x73, 0xaa, 0x81, 0x77, 0x33, 0x4d, 0xba, 0x9c, 0x69, 0xd2, 0xf7, 0x99, 0x26, 0xbd,
	0xee, 0x10, 0x4b, 0x1c, 0xfb, 0x43, 0xdd, 0x64, 0x4e, 0xd4, 0xef, 0xc8, 0xa2, 0xc4, 0x66, 0x43,
	0xc3, 0x8e, 0xbb, 0x07, 0x1d, 0x74, 0xfa, 0xd7, 0x88, 0xf0, 0xa1, 0xf1, 0xe1, 0x66, 0xf4, 0xd3,
	0x7b, 0xf2, 0x27, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xed, 0xce, 0xb1, 0xd0, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RegisterDiscounts(ctx context.Context, in *MsgRegisterDiscounts, opts ...grpc.CallOption) (*MsgRegisterDiscountsResponse, error)
	RemoveDiscounts(ctx context.Context, in *MsgRemoveDiscounts, opts ...grpc.CallOption) (*MsgRemoveDiscountsResponse, error)
	ChangeModerator(ctx context.Context, in *MsgChangeModerator, opts ...grpc.CallOption) (*MsgChangeModeratorResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterDiscounts(ctx context.Context, in *MsgRegisterDiscounts, opts ...grpc.CallOption) (*MsgRegisterDiscountsResponse, error) {
	out := new(MsgRegisterDiscountsResponse)
	err := c.cc.Invoke(ctx, "/guru.feepolicy.v1.Msg/RegisterDiscounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveDiscounts(ctx context.Context, in *MsgRemoveDiscounts, opts ...grpc.CallOption) (*MsgRemoveDiscountsResponse, error) {
	out := new(MsgRemoveDiscountsResponse)
	err := c.cc.Invoke(ctx, "/guru.feepolicy.v1.Msg/RemoveDiscounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ChangeModerator(ctx context.Context, in *MsgChangeModerator, opts ...grpc.CallOption) (*MsgChangeModeratorResponse, error) {
	out := new(MsgChangeModeratorResponse)
	err := c.cc.Invoke(ctx, "/guru.feepolicy.v1.Msg/ChangeModerator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RegisterDiscounts(context.Context, *MsgRegisterDiscounts) (*MsgRegisterDiscountsResponse, error)
	RemoveDiscounts(context.Context, *MsgRemoveDiscounts) (*MsgRemoveDiscountsResponse, error)
	ChangeModerator(context.Context, *MsgChangeModerator) (*MsgChangeModeratorResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterDiscounts(ctx context.Context, req *MsgRegisterDiscounts) (*MsgRegisterDiscountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDiscounts not implemented")
}
func (*UnimplementedMsgServer) RemoveDiscounts(ctx context.Context, req *MsgRemoveDiscounts) (*MsgRemoveDiscountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDiscounts not implemented")
}
func (*UnimplementedMsgServer) ChangeModerator(ctx context.Context, req *MsgChangeModerator) (*MsgChangeModeratorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeModerator not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterDiscounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterDiscounts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterDiscounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guru.feepolicy.v1.Msg/RegisterDiscounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterDiscounts(ctx, req.(*MsgRegisterDiscounts))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveDiscounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveDiscounts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveDiscounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guru.feepolicy.v1.Msg/RemoveDiscounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveDiscounts(ctx, req.(*MsgRemoveDiscounts))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ChangeModerator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgChangeModerator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ChangeModerator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guru.feepolicy.v1.Msg/ChangeModerator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ChangeModerator(ctx, req.(*MsgChangeModerator))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "guru.feepolicy.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDiscounts",
			Handler:    _Msg_RegisterDiscounts_Handler,
		},
		{
			MethodName: "RemoveDiscounts",
			Handler:    _Msg_RemoveDiscounts_Handler,
		},
		{
			MethodName: "ChangeModerator",
			Handler:    _Msg_ChangeModerator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guru/feepolicy/v1/tx.proto",
}

func (m *MsgRegisterDiscounts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterDiscounts) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterDiscounts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Discounts) > 0 {
		for iNdEx := len(m.Discounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Discounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ModeratorAddress) > 0 {
		i -= len(m.ModeratorAddress)
		copy(dAtA[i:], m.ModeratorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ModeratorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterDiscountsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterDiscountsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterDiscountsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRemoveDiscounts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveDiscounts) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveDiscounts) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MsgType) > 0 {
		i -= len(m.MsgType)
		copy(dAtA[i:], m.MsgType)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MsgType)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ModeratorAddress) > 0 {
		i -= len(m.ModeratorAddress)
		copy(dAtA[i:], m.ModeratorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ModeratorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveDiscountsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveDiscountsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveDiscountsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgChangeModerator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgChangeModerator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgChangeModerator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewModeratorAddress) > 0 {
		i -= len(m.NewModeratorAddress)
		copy(dAtA[i:], m.NewModeratorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewModeratorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ModeratorAddress) > 0 {
		i -= len(m.ModeratorAddress)
		copy(dAtA[i:], m.ModeratorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ModeratorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgChangeModeratorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgChangeModeratorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgChangeModeratorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterDiscounts) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModeratorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Discounts) > 0 {
		for _, e := range m.Discounts {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgRegisterDiscountsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRemoveDiscounts) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModeratorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Module)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MsgType)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRemoveDiscountsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgChangeModerator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModeratorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewModeratorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgChangeModeratorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterDiscounts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterDiscounts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterDiscounts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModeratorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModeratorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Discounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Discounts = append(m.Discounts, AccountDiscount{})
			if err := m.Discounts[len(m.Discounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterDiscountsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterDiscountsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterDiscountsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveDiscounts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveDiscounts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveDiscounts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModeratorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModeratorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveDiscountsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveDiscountsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveDiscountsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgChangeModerator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgChangeModerator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgChangeModerator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModeratorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModeratorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewModeratorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewModeratorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgChangeModeratorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgChangeModeratorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgChangeModeratorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
