name: Changelog Linter

on:
  pull_request:
    branches:
      - main
      - release/**
permissions: read-all

jobs:
  check_diff:
    # Temporarily gate lint jobs with repository variable ENABLE_LINT.
    if: ${{ vars.ENABLE_LINT == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Changelog for changes
        uses: tarides/changelog-check-action@v3
        with:
          changelog: CHANGELOG.md